name: Run tests

on:
  push:
    branches:
      - main
      - '*.x'
  # Run weekly on Monday at 1:23 UTC


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          setup.cfg
    - name: Install and update Python dependencies (binary only)
      if: ${{ ! contains( matrix.python-version, 'dev' ) }}
      run: |
        python -m pip install --only-binary ':all:' --upgrade pip setuptools wheel build
        python -m pip install --only-binary ':all:' --upgrade check-manifest pytest-cov  pytest-json-report
    - name: Try building with Python build
      run: |
        python -m build
        shasum -a 256 dist/*
    - name: Check manifest
      run: check-manifest
    - name: pytest
      env:
        COLUMNS: 120
      run: |
        pytest --color=yes -raXxs 
